### PR TITLE
Update namespace usage (had compilation errors)

### PR DESCRIPTION
**Pull request by mleonardallen**
I got compilation errors when I first tried to follow the project instructions

Errors introduced by https://github.com/udacity/CarND-Extended-Kalman-Filter-Project/commit/3641e338a163a1405c8a8fef1d1dffd1e6c35798

```
mkdir build && cd build
cmake .. && make
./ExtendedKF path/to/input.txt path/to/output.txt
```

### CODE REVIEW

**Comment by cameronwp** [comment]
good catch. we had a few issues with namespacing before. lgtm
