### ISSUE TITLE
Failed to compile for  Windows 10 VS2017,  Ubuntu, MacOS

### ISSUE THREAD

**Issue by MichaelTien8901** [udacity/CarND-Extended-Kalman-Filter-Project#37]
The merged master with 'project_v2' failed to compile as reported in udacity forum.  I tested in Windows 10 for VS2017 and Ubuntu in VirtualBox.  And somebody also report the same problem in MacOS 10.12.4.  
I believe somehow the current version of uWebSocket in github is not compatible.
[https://discussions.udacity.com/t/udacity-ekf-repository-fails-to-build/248521](https://discussions.udacity.com/t/udacity-ekf-repository-fails-to-build/248521)

**Comment by pierluigiferrari** [comment]
I can confirm that the repo fails to compile on Mac OS Sierra (10.12.4).

I cloned the [Udacity github repository for the EKF project](https://github.com/udacity/CarND-Extended-Kalman-Filter-Project) and it fails to build as is. Here is what I did:

1. I installed uWebSocket (just following the instructions on the github page since the Mac OS shell script provided by Udacity doesn't work either, i.e. I installed the latest master)
2. I cloned the above repository
3. I ran `cmake` successfully
4. When subsequently running `make`, I get the following errors below:

There seem to be two distinct errors concerning uWS that each occur 3 times:

 `candidate function not viable: no known conversion ...`

and

`error: no matching member function for call to [...]`,

where [...] is a placeholder for 'onMessage', 'onConnection', and 
'onDisconnection', respectively.

Here is the full log:

        Scanning dependencies of target ExtendedKF
        [ 20%] Building CXX object CMakeFiles/ExtendedKF.dir/main.cpp.o
        /Users/pierluigiferrari/Downloads/CarND-Extended-Kalman-Filter-Project-master/src/main.cpp:41:5: error: no
              matching member function for call to 'onMessage'
          h.onMessage([&fusionEKF,&tools,&estimations,&ground_truth](uWS::WebSocket<uWS::SERVER> ws, char *data...
          ~~^~~~~~~~~
        /usr/local/include/uWS/Group.h:69:10: note: candidate function not viable: no known conversion from '(lambda at
              /Users/pierluigiferrari/Downloads/CarND-Extended-Kalman-Filter-Project-master/src/main.cpp:41:15)' to
              'std::function<void (WebSocket<true> *, char *, size_t, OpCode)>' (aka 'function<void (WebSocket<true> *,
              char *, unsigned long, uWS::OpCode)>') for 1st argument
            void onMessage(std::function<void(WebSocket<isServer> *, char *, size_t, OpCode)> handler);
                 ^
        /usr/local/include/uWS/Group.h:69:10: note: candidate function not viable: no known conversion from '(lambda at
              /Users/pierluigiferrari/Downloads/CarND-Extended-Kalman-Filter-Project-master/src/main.cpp:41:15)' to
              'std::function<void (WebSocket<false> *, char *, size_t, OpCode)>' (aka 'function<void (WebSocket<false>
              *, char *, unsigned long, uWS::OpCode)>') for 1st argument
        /Users/pierluigiferrari/Downloads/CarND-Extended-Kalman-Filter-Project-master/src/main.cpp:165:5: error: no
              matching member function for call to 'onConnection'
          h.onConnection([&h](uWS::WebSocket<uWS::SERVER> ws, uWS::HttpRequest req) {
          ~~^~~~~~~~~~~~
        /usr/local/include/uWS/Group.h:67:10: note: candidate function not viable: no known conversion from '(lambda at
              /Users/pierluigiferrari/Downloads/CarND-Extended-Kalman-Filter-Project-master/src/main.cpp:165:18)' to
              'std::function<void (WebSocket<true> *, HttpRequest)>' for 1st argument
            void onConnection(std::function<void(WebSocket<isServer> *, HttpRequest)> handler);
                 ^
        /usr/local/include/uWS/Group.h:67:10: note: candidate function not viable: no known conversion from '(lambda at
              /Users/pierluigiferrari/Downloads/CarND-Extended-Kalman-Filter-Project-master/src/main.cpp:165:18)' to
              'std::function<void (WebSocket<false> *, HttpRequest)>' for 1st argument
        /Users/pierluigiferrari/Downloads/CarND-Extended-Kalman-Filter-Project-master/src/main.cpp:169:5: error: no
              matching member function for call to 'onDisconnection'
          h.onDisconnection([&h](uWS::WebSocket<uWS::SERVER> ws, int code, char *message, size_t length) {
          ~~^~~~~~~~~~~~~~~
        /usr/local/include/uWS/Group.h:70:10: note: candidate function not viable: no known conversion from '(lambda at
              /Users/pierluigiferrari/Downloads/CarND-Extended-Kalman-Filter-Project-master/src/main.cpp:169:21)' to
              'std::function<void (WebSocket<true> *, int, char *, size_t)>' (aka 'function<void (WebSocket<true> *,
              int, char *, unsigned long)>') for 1st argument
            void onDisconnection(std::function<void(WebSocket<isServer> *, int code, char *message, size_t lengt...
                 ^
        /usr/local/include/uWS/Group.h:70:10: note: candidate function not viable: no known conversion from '(lambda at
              /Users/pierluigiferrari/Downloads/CarND-Extended-Kalman-Filter-Project-master/src/main.cpp:169:21)' to
              'std::function<void (WebSocket<false> *, int, char *, size_t)>' (aka 'function<void (WebSocket<false> *,
              int, char *, unsigned long)>') for 1st argument
        3 errors generated.
        make[2]: *** [CMakeFiles/ExtendedKF.dir/main.cpp.o] Error 1
        make[1]: *** [CMakeFiles/ExtendedKF.dir/all] Error 2
        make: *** [all] Error 2

Note that I simply cloned the repository and tried to build it according to the instructions - I did not make any changes to any of the files.

My system is Mac OS Sierra (10.12.4)

**Comment by MichaelTien8901** [comment]
For ubuntu, we should use install-ubuntu.sh to install the right version of uWebSockets.  The latest version is not compatible with this project.

sudo ./install-ubuntu.sh

**Comment by pierluigiferrari** [comment]
`install-mac.sh` is not working on Mac OS 10.11 or later though, see this issue here: #35
